// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlOeFzyNjNl3BOdwhEWgy5CvOIYPSZvgg',
    appId: '1:850938603969:web:0f672e64bb91a1bc5a2740',
    messagingSenderId: '850938603969',
    projectId: 'service-hub-26d86',
    authDomain: 'service-hub-26d86.firebaseapp.com',
    storageBucket: 'service-hub-26d86.firebasestorage.app',
    measurementId: 'G-BY9LP63EYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjkcsTUp0AUIi6L6dPwMFSbBpBbqwbgIo',
    appId: '1:850938603969:android:b99ec4886c0266265a2740',
    messagingSenderId: '850938603969',
    projectId: 'service-hub-26d86',
    storageBucket: 'service-hub-26d86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4VK5zwM8D9ZVwl06iu1DFIDl2WDGD67A',
    appId: '1:850938603969:ios:8016fe68b4ed1de95a2740',
    messagingSenderId: '850938603969',
    projectId: 'service-hub-26d86',
    storageBucket: 'service-hub-26d86.firebasestorage.app',
    iosBundleId: 'com.example.serviceHubAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4VK5zwM8D9ZVwl06iu1DFIDl2WDGD67A',
    appId: '1:850938603969:ios:8016fe68b4ed1de95a2740',
    messagingSenderId: '850938603969',
    projectId: 'service-hub-26d86',
    storageBucket: 'service-hub-26d86.firebasestorage.app',
    iosBundleId: 'com.example.serviceHubAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlOeFzyNjNl3BOdwhEWgy5CvOIYPSZvgg',
    appId: '1:850938603969:web:bec2b4c24cd4da825a2740',
    messagingSenderId: '850938603969',
    projectId: 'service-hub-26d86',
    authDomain: 'service-hub-26d86.firebaseapp.com',
    storageBucket: 'service-hub-26d86.firebasestorage.app',
    measurementId: 'G-YSVN4W6YZ8',
  );
}
